### ISSUE TITLE
Exposing rendering output to string/single file via CLI

### ISSUE THREAD

**Issue by bobcats** [maizzle/cli#103]
Hi there,

I'm working on integrating Maizzle into a Rails app a la https://github.com/sighmon/mjml-rails and I think it would be useful to be able to build a template individually as a string (and be able to specify text vs. html), rather than the whole project.

Is that something you'd be willing to support through the CLI? I see that there's an `Output.toString` which seems like it would work for what I'm trying to accomplish, but I could very well be going in the wrong direction. Happy to take another approach if you've got any ideas!

Thanks!

**Comment by cossssmin** [comment]
Use the `render` method:

https://maizzle.com/docs/nodejs/

**Comment by bobcats** [comment]
Thanks!
