### ISSUE TITLE
Git clone with the github url twice

### ISSUE THREAD

**Issue by mikevosje** [maizzle/cli#30]
During the `maizzle new https://github.com/maizzle/starter-amp4email.git` command, the gitrepository is being cloned, but this clone command has the given github url twice:

`git clone https://github.com/maizzle/starter-amp4email.git https://github.com/maizzle/starter-amp4email.git --single-branch`

One must be deleted, so that the clone is going right.

Here a screenshot of the command execution
<img width="1267" alt="Schermafbeelding 2020-04-28 om 21 10 33" src="https://user-images.githubusercontent.com/3897623/80527486-b6027180-8994-11ea-9d41-6cec32f76275.png">

**Comment by cossssmin** [comment]
Thanks for spotting it, will look into it first thing in the morning 👍

**Comment by cossssmin** [comment]
@mikevosje fixed and released [`v1.0.1`](https://github.com/maizzle/cli/releases/tag/v1.0.1)
