### ISSUE TITLE
Incompatibiliy with monorepo

### ISSUE THREAD

**Issue by ibraelillo** [maizzle/cli#44]
Hello, 

I'm trying to work with maizzle framework in a monorepo structure built with @lerna, and when trying to build the project completely the cli is throwing an error. This is because in monorepos, node_modules are symlinked to root folder, and the cli is not following the symlink. 

The action line is breaking my build 

```
  cli
    .command('build [env]')
    .description('compile email templates and output them to disk')
    .action(env => importCwd('./node_modules/@maizzle/framework/src').build(env))
```

**Comment by cossssmin** [comment]
I will accept a PR (with tests!) that fixes this issue 👍

**Comment by cossssmin** [comment]
Does the `--bin` option in [v1.2.0](https://github.com/maizzle/cli/releases/tag/v1.2.0) help in this case?

**Comment by khaledosman** [comment]
I had the same issue was getting this error when trying to run maizzle after moving the project to my lerna + yarn workspaces powered monorepo

```
Error: Framework not found

Make sure to run this command in your Maizzle project root, with dependencies installed.
```

using the `--bin` flag worked for me, thanks!

**Comment by danawoodman** [comment]
Took me a while to find this, maybe the error message should mention this about mono repos?
