### ISSUE TITLE
Unable to use maizzle commands.

### ISSUE THREAD

**Issue by michael-andreuzza** [maizzle/cli#75]
Steps:
1.-
`npm install -g @maizzle/cli
`
2.-
`maizzle new
`
After this command I get this.
`maizzle: command not found`

It's been working fine before on another computer but not anymore.

**Comment by cossssmin** [comment]
Looks like it didn’t install properly. 

Check with `npm list -g @maizzle/cli` and try installing it again.

**Comment by michael-andreuzza** [comment]
I anm still getting the issue.

`mike-andreuzza@mikeandreuzza-ThinkPad-T410s:~$ npm i -g @maizzle/cli
/home/mike-andreuzza/.npm-global/bin/maizzle -> /home/mike-andreuzza/.npm-global/lib/node_modules/@maizzle/cli/bin/maizzle
+ @maizzle/cli@1.0.4
updated 1 package in 13.046s
mike-andreuzza@mikeandreuzza-ThinkPad-T410s:~$ npm list -g @maizzle/cli
/home/mike-andreuzza/.npm-global/lib
└── @maizzle/cli@1.0.4 

mike-andreuzza@mikeandreuzza-ThinkPad-T410s:~$ npm i -g @maizzle/cli
/home/mike-andreuzza/.npm-global/bin/maizzle -> /home/mike-andreuzza/.npm-global/lib/node_modules/@maizzle/cli/bin/maizzle
+ @maizzle/cli@1.0.4
updated 1 package in 11.649s
mike-andreuzza@mikeandreuzza-ThinkPad-T410s:~$ maizzle new
maizzle: command not found
mike-andreuzza@mikeandreuzza-ThinkPad-T410s:~$`

**Comment by cossssmin** [comment]
Probably a permissions/user issue, maybe have a look here:

https://medium.com/@jagatjyoti.1si13cs040/npm-g-install-npm-package-not-working-as-desired-why-why-why-19795abf0b59

Sorry I can’t help more, but this is not an issue with the package itself.
